services:
  fhir-server:
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    
  flask-app:
    build: .
    container_name: flask-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - fhir-server

  celery-worker:
    build: .
    container_name: celery_worker
    command: celery -A api.write_to_fhir_task worker --loglevel=info
    working_dir: /app
    depends_on:
      - redis
    volumes:
      - .:/app